// <auto-generated />
using Flowey.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowey.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230930171326_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Flowey.Services.ProductAPI.Models.Dto.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Цветы",
                            Description = "Розы колючие",
                            ImageUrl = "",
                            Name = "Розы",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Цветы",
                            Description = "Кросивый",
                            ImageUrl = "",
                            Name = "Лилии",
                            Price = 150.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Комнатные растения",
                            Description = "Комнатные растения",
                            ImageUrl = "",
                            Name = "Фикус",
                            Price = 500.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Комнатные растения",
                            Description = "Домашнее с большими листьями",
                            ImageUrl = "",
                            Name = "Монстера",
                            Price = 1500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
